"""lesson_start

Revision ID: 58e989dc269d
Revises: 5009e38bea7b
Create Date: 2022-09-18 19:45:12.251206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58e989dc269d'
down_revision = '5009e38bea7b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lesson', sa.Column('start', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lesson', 'start')
    # ### end Alembic commands ###
