"""constraints

Revision ID: 7d1b3b890afd
Revises: 58e989dc269d
Create Date: 2022-09-18 22:23:41.472890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d1b3b890afd'
down_revision = '58e989dc269d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lesson', 'course_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('lesson', 'teacher_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('lesson', 'name')
    op.execute("INSERT INTO \"user\" VALUES (default, 'admin', '$pbkdf2-sha256$29000$4fxfq5UyJiREqPV.j3Eu5Q$5VjtGw6z/1dS77qWe6Bx8S6lzod7XoUGHoxsnktZEQ0')")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lesson', sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('lesson', 'teacher_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('lesson', 'course_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
